name: Test

on:
  push:
    paths-ignore:
      - "docs/**"
      - "README.md"
      - "LICENSE"
      - ".editorconfig"
    branches:
      - main
      - master
  pull_request:
    paths-ignore:
      - "docs/**"
      - "README.md"
      - "LICENSE"
      - ".editorconfig"
    branches:
      - main
      - master

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        node: [14.x, 16.x]

    steps:
      - uses: actions/4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          cache: "npm"
          node-version: ${{ matrix.node }}
      - run: npm ci
      - run: npm run test
